/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Event */
        post: operations["core_api_events_capture_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capture/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Event Batch */
        post: operations["core_api_events_capture_event_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["core_api_events_list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Insights */
        get: operations["core_api_events_get_event_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["core_api_events_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["core_api_events_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** StatusResponse */
        StatusResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** EventCaptureSchema */
        EventCaptureSchema: {
            /** Distinct Id */
            distinct_id: string;
            /** Event Name */
            event_name: string;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
            /** Event Uuid */
            event_uuid?: string | null;
            /** Sent At */
            sent_at?: string | null;
        };
        /** BatchStatusResponse */
        BatchStatusResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Accepted */
            accepted: number;
        };
        /** EventBatchCaptureSchema */
        EventBatchCaptureSchema: {
            /** Events */
            events: components["schemas"]["EventCaptureSchema"][];
        };
        /** EventResponseSchema */
        EventResponseSchema: {
            /** Uuid */
            uuid: string;
            /** ID */
            id?: number | null;
            /**
             * Distinct Id
             * @description User ID
             */
            distinct_id: string;
            /** Event Name */
            event_name: string;
            /**
             * Properties
             * @description Flexible JSONB field for event properties
             */
            properties?: Record<string, never> | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InsightDataPoint */
        InsightDataPoint: {
            /** Time */
            time: string;
            /** Count */
            count: number;
        };
        /** HealthStatusResponse */
        HealthStatusResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Cache */
            cache: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_api_events_capture_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCaptureSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    core_api_events_capture_event_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventBatchCaptureSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatusResponse"];
                };
            };
        };
    };
    core_api_events_list_events: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseSchema"][];
                };
            };
        };
    };
    core_api_events_get_event_insights: {
        parameters: {
            query?: {
                lookback_minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightDataPoint"][];
                };
            };
        };
    };
    core_api_events_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatusResponse"];
                };
            };
        };
    };
    core_api_events_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatusResponse"];
                };
            };
        };
    };
}
