"""
Django settings for telemetry_taco project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, True)  # Default to True for development safety
)

# Read .env file if it exists
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG defaults to True for local development convenience.
# Explicitly set DEBUG=False in production environment.
DEBUG = env("DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be explicitly set via environment variable in ALL environments
# (both development and production) to prevent accidental deployment with insecure keys.
# No default value is provided as a security measure.
if "SECRET_KEY" not in os.environ:
    raise ValueError(
        "SECRET_KEY must be explicitly set via environment variable. "
        "This is required for security in both development and production environments.\n\n"
        "To generate a secure secret key, run:\n"
        "  python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'\n\n"
        "Then add it to your .env file:\n"
        "  SECRET_KEY=your-generated-secret-key-here\n\n"
        "For local development, you can add this to backend/.env"
    )

# Get the SECRET_KEY from environment
SECRET_KEY = env("SECRET_KEY")

# Validate that SECRET_KEY is not using any known insecure defaults
# This prevents accidental use of example/insecure values
# Note: start.sh now generates secure keys, but we keep these in the list to catch
# manually set insecure values or values from old .env files
insecure_defaults = [
    "django-insecure-change-me-in-production",
    "django-insecure-dev-only-change-me-in-production",
    "changeme",
    "secret",
    "your-secret-key-here",
]

if SECRET_KEY in insecure_defaults:
    raise ValueError(
        f"SECRET_KEY cannot use the insecure default value '{SECRET_KEY}'. "
        "Generate a secure secret key and set it via the SECRET_KEY environment variable.\n\n"
        "To generate a secure secret key, run:\n"
        "  python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

# Additional validation: ensure SECRET_KEY has minimum length
if len(SECRET_KEY) < 50:
    raise ValueError(
        "SECRET_KEY appears to be too short. Django secret keys should be at least 50 characters. "
        "Generate a secure secret key using:\n"
        "  python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "0.0.0.0"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "telemetry_taco.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "telemetry_taco.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": env.db(
        "DATABASE_URL", default="postgresql://postgres:postgres@localhost:5432/telemetry_taco"
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
# In development, allow all localhost origins for flexibility
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    # Allow all localhost origins in development
    CORS_ALLOW_ALL_ORIGINS = False  # Explicitly set to False for security
else:
    # Production: Only allow specific origins
    CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Celery Configuration
CELERY_BROKER_URL = env("REDIS_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("REDIS_URL", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Cache Configuration (for rate limiting)
# Uses Redis for rate limiting storage (separate DB from Celery)
# django-redis provides robust Redis caching with connection pooling
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://localhost:6379/1"),  # Use DB 1 for cache
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Rate Limiting Configuration
# django-ratelimit uses the default cache backend (Redis) for rate limit tracking
RATELIMIT_USE_CACHE = "default"

# Environment detection for default rate limits
# Use ENVIRONMENT variable (development/staging/production) instead of DEBUG
# This is safer than using DEBUG, which should never be True in production
ENVIRONMENT = env("ENVIRONMENT", default="production").lower()

# Configurable rate limits for API endpoints
# Format: "number/period" where period is s (second), m (minute), h (hour), d (day)
# Examples: "1000/h" = 1000 per hour, "100/m" = 100 per minute
# Defaults vary by environment: development has higher limits for testing
if ENVIRONMENT == "development":
    DEFAULT_RATE_LIMIT_CAPTURE_EVENT = "10000/h"
    DEFAULT_RATE_LIMIT_LIST_EVENTS = "1000000/h"  # Very high limit for development
    DEFAULT_RATE_LIMIT_GET_INSIGHTS = "1000/h"
else:
    # Production/staging defaults (more restrictive)
    DEFAULT_RATE_LIMIT_CAPTURE_EVENT = "1000/h"
    DEFAULT_RATE_LIMIT_LIST_EVENTS = "10000/h"
    DEFAULT_RATE_LIMIT_GET_INSIGHTS = "300/h"

# Allow explicit override via environment variables (takes precedence over environment-based defaults)
RATE_LIMIT_CAPTURE_EVENT = env("RATE_LIMIT_CAPTURE_EVENT", default=DEFAULT_RATE_LIMIT_CAPTURE_EVENT)
RATE_LIMIT_LIST_EVENTS = env("RATE_LIMIT_LIST_EVENTS", default=DEFAULT_RATE_LIMIT_LIST_EVENTS)
RATE_LIMIT_GET_INSIGHTS = env("RATE_LIMIT_GET_INSIGHTS", default=DEFAULT_RATE_LIMIT_GET_INSIGHTS)
